// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWdo5h9LI6mJMXga8UU8JjkMM4OM6Bfos',
    appId: '1:281054250824:web:3325f02d50994f2782957d',
    messagingSenderId: '281054250824',
    projectId: 'hella-23ea4',
    authDomain: 'hella-23ea4.firebaseapp.com',
    storageBucket: 'hella-23ea4.firebasestorage.app',
    measurementId: 'G-BJDB6ZZQNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNke9Fm_j-k618fDi9NQjLESc4TrZ_vso',
    appId: '1:281054250824:android:b549bbdccb50520182957d',
    messagingSenderId: '281054250824',
    projectId: 'hella-23ea4',
    storageBucket: 'hella-23ea4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHIjeb1gR_Z0RcAUZf3Y2sJBr7eONwhxI',
    appId: '1:281054250824:ios:3e3662ec4f9bda9082957d',
    messagingSenderId: '281054250824',
    projectId: 'hella-23ea4',
    storageBucket: 'hella-23ea4.firebasestorage.app',
    iosClientId: '281054250824-f66tqm2qhrclfrgu2lp17ntq48vfo81p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHIjeb1gR_Z0RcAUZf3Y2sJBr7eONwhxI',
    appId: '1:281054250824:ios:3e3662ec4f9bda9082957d',
    messagingSenderId: '281054250824',
    projectId: 'hella-23ea4',
    storageBucket: 'hella-23ea4.firebasestorage.app',
    iosClientId: '281054250824-f66tqm2qhrclfrgu2lp17ntq48vfo81p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWdo5h9LI6mJMXga8UU8JjkMM4OM6Bfos',
    appId: '1:281054250824:web:339f77506cd8370182957d',
    messagingSenderId: '281054250824',
    projectId: 'hella-23ea4',
    authDomain: 'hella-23ea4.firebaseapp.com',
    storageBucket: 'hella-23ea4.firebasestorage.app',
    measurementId: 'G-47V1F6LHVX',
  );
}
